### PR TITLE
Fix for <iOS9 scanner crashes

### PR DESCRIPTION
**Pull request by franek-scandit**
Fix for #42

### CODE REVIEW

**Comment by moritzhartmeier** [comment]
@franek-scandit can you cherry pick it into 5.6 as well please?

**Comment by franek-scandit** [comment]
@moritzhartmeier done

**Comment by lucatorella** [comment]
did you see my comment in the issue? Probably `strongSelf.onSettingsApplied(nil);` is a better fix.

**Comment by franek-scandit** [comment]
@lucatorella Unfortunately I didn't. Why was the empty dictionary passed then?

**Comment by lucatorella** [comment]
Interestingly enough, Airbnb does the same in their Maps plugin 
https://github.com/react-community/react-native-maps/search?utf8=✓&q=onMapREady&type= `mapView.onMapReady(@{});`, but I can't find the minimum supported version of their plugin

**Comment by franek-scandit** [comment]
@lucatorella @moritzhartmeier I cherry picked Luca's changes and committed them on 5.6 branch as well.

**Pull request merged**
